Introduce `ag services:info [name]`
Depends on arigatomachine/registry#111
Related arigatomachine/cli#171

You can now view a service using `ag services:info [name]` which
includes validation for the provided name (it must be a slug).

Example:

**Happy Path - Found the Service**

```
Ians-MacBook-Pro-2:cli ianlivingstone$ bin/arigato services:info testing
Service testing:

Nothing here yet! Work in progress :)
```

**Sad -- Service does not exist**

```
Ians-MacBook-Pro-2:cli ianlivingstone$ bin/arigato services:info fsfs

Retrieval of service failed!

Error: service not found
    at Client._extractError (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/api/client.js:145:13)
    at Request._callback (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/api/client.js:111:28)
    at Request.self.callback (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13) at Request.emit (events.js:172:7) at Request.<anonymous> (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20) at Request.emit (events.js:169:7) at IncomingMessage.<anonymous> (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
```

**Sad - not logged in**

```
Ians-MacBook-Pro-2:cli ianlivingstone$ bin/arigato services:info fsfs

Retrieval of service failed!

Error: must authenticate first
    at Client.auth (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/api/client.js:56:11)
    at /Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/services/get.js:38:12
    at lib$es6$promise$$internal$$initializePromise (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/es6-promise/dist/es6-promise.js:408:9)
    at new lib$es6$promise$promise$$Promise (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/es6-promise/dist/es6-promise.js:581:60)
    at Object.serviceGet.execute (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/services/get.js:31:10)
    at /Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/cmds/services/info.js:13:20
    at lib$es6$promise$$internal$$initializePromise (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/es6-promise/dist/es6-promise.js:408:9)
    at new lib$es6$promise$promise$$Promise (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/node_modules/es6-promise/dist/es6-promise.js:581:60)
    at Function.<anonymous> (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/cmds/services/info.js:12:12)
    at wrap (/Users/ianlivingstone/code/src/github.com/arigatomachine/cli/cli/lib/cli/wrap.js:8:14)
```

Later on we will add more content here once we actually have it.
Examples content could include:

- Membership and access roles
- Environments
- Org information

Closes arigatomachine/cli#182